### ISSUE TITLE
What is dind used for, and is it necessary or can I remove it from the chart?

### ISSUE THREAD

**Issue by lucavallin** [lazybit-ch/actions-runner#2]

**Comment by masseybradley** [comment]
The [`dind`](https://github.com/lazybit-ch/dind/tree/master/dind) dependency is a [docker-in-docker](https://hub.docker.com/_/docker) statefulset deployment that you can configure with the `actions-runner` - you can disable it during the deployment (`helm install myrelease --set dind.enabled=false`) if you don't need it (i.e. are sharing the `docker` daemon from the host, however that's not suggested).

**Comment by lucavallin** [comment]
Thank you!
